apiVersion: v1
kind: Service
metadata:
  name: 'echo-server'
  namespace: appveen
spec:
  type: LoadBalancer
  selector:
    app: 'echo-server'
    release: '1.0.0'
  ports:
    - protocol: TCP
      name: 'echo-server'
      port: 31000
      targetPort: 3000
      nodePort: 31000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: 'echo-server'
  namespace: appveen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'echo-server'
      release: '1.0.0'
  template:
    metadata:
      labels:
        app: 'echo-server'
        release: '1.0.0'
    spec:
      containers:
        - name: 'echo-server'
          image: 'odp:echo-server'
          ports:
            - containerPort: 3000